export const ErrorCode = {
  INVALID_PARAMS: 'INVALID_PARAMS',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  PASSWORD_TOO_SMALL: 'PASSWORD_TOO_SMALL',
  UNKNOWN: 'UNKNOWN',
  INVALID_EMAIL_ERROR: 'INVALID_EMAIL_ERROR',
  USER_WAS_NOT_FOUND: 'USER_WAS_NOT_FOUND',
  WRONG_PASSWORD_ERROR: 'WRONG_PASSWORD_ERROR',
}
